In [95]:
import pandas as pd
import numpy as np

In [96]:
df = pd.read_csv("../data/real_estate_agency.csv")

In [97]:
print(f"Количество строк = {df.shape[0]}")
print(f"Количество стобцов = {df.shape[1]}")
display(df.head())
df.info()

Количество строк = 23368
Количество стобцов = 25

,Unnamed: 0,ID объявления,Количество комнат,Тип,Метро,Адрес,"Площадь, м2",Дом,Парковка,Цена,...,Окна,Санузел,Можно с детьми/животными,Дополнительно,Название ЖК,Серия дома,"Высота потолков, м",Лифт,Мусоропровод,Ссылка на объявление
0,0,271271157,4,Квартира,м. Смоленская (9 мин пешком),"Москва, улица Новый Арбат, 27",200.0/20.0,"5/16, Монолитный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",...,NaN,NaN,"Можно с детьми, Можно с животными","Мебель в комнатах, Мебель на кухне, Ванна, Душ...","Новый Арбат, 2010",NaN,3.0,"Пасс (4), Груз (1)",Да,https://www.cian.ru/rent/flat/271271157
1,1,271634126,4,Квартира,м. Смоленская (8 мин пешком),"Москва, улица Новый Арбат, 27",198.0/95.0/18.0,"5/16, Монолитно-кирпичный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",...,На улицу и двор,"Совмещенный (2), Раздельный (1)",Можно с детьми,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",Новый Арбат,NaN,3.5,"Пасс (1), Груз (1)",Нет,https://www.cian.ru/rent/flat/271634126
2,2,271173086,"4, Оба варианта",Квартира,м. Смоленская (7 мин пешком),"Москва, улица Новый Арбат, 27",200.0/116.0/4.0,5/16,подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",...,На улицу и двор,Совмещенный (3),Можно с детьми,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",Новый Арбат,NaN,3.2,Пасс (1),NaN,https://www.cian.ru/rent/flat/271173086
3,3,272197456,"4, Оба варианта",Квартира,м. Смоленская (3 мин пешком),"Москва, переулок Плотников, 21С1",170.0/95.0/17.0,5/6,подземная,"400000.0 руб./ За месяц, Залог - 400000 руб., ...",...,На улицу и двор,Совмещенный (3),Можно с животными,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",NaN,NaN,3.2,Пасс (1),NaN,https://www.cian.ru/rent/flat/272197456
4,4,273614615,2,Квартира,м. Арбатская (7 мин пешком),"Москва, улица Новый Арбат, 15",58.0/38.0/5.0,"12/26, Панельный",NaN,"225000.0 руб./ За месяц, Залог - 225000 руб., ...",...,На улицу и двор,Совмещенный (2),NaN,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",The Book,NaN,3.9,"Пасс (1), Груз (1)",Да,https://www.cian.ru/rent/flat/273614615

<class 'pandas.DataFrame'>
RangeIndex: 23368 entries, 0 to 23367
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                23368 non-null  int64
 1   ID  объявления            23368 non-null  int64
 2   Количество комнат         22327 non-null  str
 3   Тип                       23368 non-null  str
 4   Метро                     22053 non-null  str
 5   Адрес                     23368 non-null  str
 6   Площадь, м2               23368 non-null  str
 7   Дом                       23368 non-null  str
 8   Парковка                  9951 non-null   str
 9   Цена                      23368 non-null  str
 10  Телефоны                  23368 non-null  str
 11  Описание                  23368 non-null  str
 12  Ремонт                    20613 non-null  str
 13  Площадь комнат, м2        14458 non-null  str
 14  Балкон                    15390 non-null  str
 15  Окна                      16755 non-null  str
 16  Санузел                   20696 non-null  str
 17  Можно с детьми/животными  17272 non-null  str
 18  Дополнительно             23011 non-null  str
 19  Название ЖК               5848 non-null   str
 20  Серия дома                2163 non-null   str
 21  Высота потолков, м        11206 non-null  float64
 22  Лифт                      17868 non-null  str
 23  Мусоропровод              12846 non-null  str
 24  Ссылка на объявление      23368 non-null  str
dtypes: float64(1), int64(2), str(22)
memory usage: 42.5 MB

In [98]:
df = df.drop(columns=["Unnamed: 0"])

In [99]:
print(f"Количество строк: {df.shape[0]}")
print(f"Количество столбцов: {df.shape[1]}")

Количество строк: 23368
Количество столбцов: 24

In [100]:
print(f"Количество дубликатов: {df.duplicated().sum()}")

Количество дубликатов: 0

In [101]:
df.isna().sum()

ID  объявления                  0
Количество комнат            1041
Тип                             0
Метро                        1315
Адрес                           0
Площадь, м2                     0
Дом                             0
Парковка                    13417
Цена                            0
Телефоны                        0
Описание                        0
Ремонт                       2755
Площадь комнат, м2           8910
Балкон                       7978
Окна                         6613
Санузел                      2672
Можно с детьми/животными     6096
Дополнительно                 357
Название ЖК                 17520
Серия дома                  21205
Высота потолков, м          12162
Лифт                         5500
Мусоропровод                10522
Ссылка на объявление            0
dtype: int64

In [102]:
missing = df.isna().sum()

In [103]:
missing[missing > 0]

Количество комнат            1041
Метро                        1315
Парковка                    13417
Ремонт                       2755
Площадь комнат, м2           8910
Балкон                       7978
Окна                         6613
Санузел                      2672
Можно с детьми/животными     6096
Дополнительно                 357
Название ЖК                 17520
Серия дома                  21205
Высота потолков, м          12162
Лифт                         5500
Мусоропровод                10522
dtype: int64

In [104]:
missing = missing[missing > 0]

In [105]:
((missing / len(df)) * 100).round(2)

Количество комнат            4.45
Метро                        5.63
Парковка                    57.42
Ремонт                      11.79
Площадь комнат, м2          38.13
Балкон                      34.14
Окна                        28.30
Санузел                     11.43
Можно с детьми/животными    26.09
Дополнительно                1.53
Название ЖК                 74.97
Серия дома                  90.74
Высота потолков, м          52.05
Лифт                        23.54
Мусоропровод                45.03
dtype: float64

In [106]:
missing_percent = ((missing / len(df)) * 100).round(2)

In [107]:
missing_df = pd.DataFrame({
    "Пропусков": missing,
    "Пропусков, %": missing_percent
})

In [108]:
missing_df.sort_values("Пропусков", ascending=False)

                          Пропусков  Пропусков, %
Серия дома                    21205         90.74
Название ЖК                   17520         74.97
Парковка                      13417         57.42
Высота потолков, м            12162         52.05
Мусоропровод                  10522         45.03
Площадь комнат, м2             8910         38.13
Балкон                         7978         34.14
Окна                           6613         28.30
Можно с детьми/животными       6096         26.09
Лифт                           5500         23.54
Ремонт                         2755         11.79
Санузел                        2672         11.43
Метро                          1315          5.63
Количество комнат              1041          4.45
Дополнительно                   357          1.53

In [109]:
missing_df = missing_df.sort_values("Пропусков", ascending=False)

In [110]:
display(missing_df)

                          Пропусков  Пропусков, %
Серия дома                    21205         90.74
Название ЖК                   17520         74.97
Парковка                      13417         57.42
Высота потолков, м            12162         52.05
Мусоропровод                  10522         45.03
Площадь комнат, м2             8910         38.13
Балкон                         7978         34.14
Окна                           6613         28.30
Можно с детьми/животными       6096         26.09
Лифт                           5500         23.54
Ремонт                         2755         11.79
Санузел                        2672         11.43
Метро                          1315          5.63
Количество комнат              1041          4.45
Дополнительно                   357          1.53

In [111]:
display(df.dtypes)

ID  объявления                int64
Количество комнат               str
Тип                             str
Метро                           str
Адрес                           str
Площадь, м2                     str
Дом                             str
Парковка                        str
Цена                            str
Телефоны                        str
Описание                        str
Ремонт                          str
Площадь комнат, м2              str
Балкон                          str
Окна                            str
Санузел                         str
Можно с детьми/животными        str
Дополнительно                   str
Название ЖК                     str
Серия дома                      str
Высота потолков, м          float64
Лифт                            str
Мусоропровод                    str
Ссылка на объявление            str
dtype: object

In [112]:
df["Валюта"] = df["Цена"]

In [113]:
df.head(0)

Empty DataFrame
Columns: [ID  объявления, Количество комнат, Тип, Метро, Адрес, Площадь, м2, Дом, Парковка, Цена, Телефоны, Описание, Ремонт, Площадь комнат, м2, Балкон, Окна, Санузел, Можно с детьми/животными, Дополнительно, Название ЖК, Серия дома, Высота потолков, м, Лифт, Мусоропровод, Ссылка на объявление, Валюта]
Index: []

[0 rows x 25 columns]

In [114]:
display(df["Цена"].str.extract(r"^[\d.]+\s*([^\s/]+)")[0].value_counts(dropna=False))

0
руб.    23344
$          14
€          10
Name: count, dtype: int64

In [115]:
display(
    df["Цена"]
    .str.extract(r"^[\d.]+\s*([^\s/]+)")[0]
    .value_counts(dropna=False)
    .head(10000)
)

0
руб.    23344
$          14
€          10
Name: count, dtype: int64

In [116]:
df["Валюта"] = df["Цена"].str.extract(r"^[\d.]+\s*([^\s/]+)")[0]

In [117]:
df["Цена числом"] = df["Цена"].str.extract(r"^([\d.]+)")[0].astype(float)

In [118]:
df.head(0)

Empty DataFrame
Columns: [ID  объявления, Количество комнат, Тип, Метро, Адрес, Площадь, м2, Дом, Парковка, Цена, Телефоны, Описание, Ремонт, Площадь комнат, м2, Балкон, Окна, Санузел, Можно с детьми/животными, Дополнительно, Название ЖК, Серия дома, Высота потолков, м, Лифт, Мусоропровод, Ссылка на объявление, Валюта, Цена числом]
Index: []

[0 rows x 26 columns]

In [119]:
display(df[["Цена", "Валюта", "Цена числом"]].head(10))

                                                Цена Валюта  Цена числом
0  500000.0 руб./ За месяц, Залог - 500000 руб., ...   руб.     500000.0
1  500000.0 руб./ За месяц, Залог - 500000 руб., ...   руб.     500000.0
2  500000.0 руб./ За месяц, Залог - 500000 руб., ...   руб.     500000.0
3  400000.0 руб./ За месяц, Залог - 400000 руб., ...   руб.     400000.0
4  225000.0 руб./ За месяц, Залог - 225000 руб., ...   руб.     225000.0
5  470000.0 руб./ За месяц, Залог - 470000 руб., ...   руб.     470000.0
6  350000.0 руб./ За месяц, Залог - 350000 руб., ...   руб.     350000.0
7  250000.0 руб./ За месяц, Залог - 250000 руб., ...   руб.     250000.0
8  130000.0 руб./ За месяц, Залог - 130000 руб., ...   руб.     130000.0
9  210000.0 руб./ За месяц, Залог - 210000 руб., ...   руб.     210000.0

In [120]:
display(df["Валюта"].value_counts(dropna=False))

Валюта
руб.    23344
$          14
€          10
Name: count, dtype: int64

In [121]:
print("Пропуски в цене:", df["Цена числом"].isna().sum())
print("Пропуски в валюте:", df["Валюта"].isna().sum())

Пропуски в цене: 0
Пропуски в валюте: 0

In [122]:
df_rub = df[df["Валюта"] == "руб."].copy()

In [123]:
print("Количество рублёвых объявлений:", len(df_rub))

Количество рублёвых объявлений: 23344

In [124]:
display(df_rub[["Цена", "Валюта", "Цена числом"]].head())

                                                Цена Валюта  Цена числом
0  500000.0 руб./ За месяц, Залог - 500000 руб., ...   руб.     500000.0
1  500000.0 руб./ За месяц, Залог - 500000 руб., ...   руб.     500000.0
2  500000.0 руб./ За месяц, Залог - 500000 руб., ...   руб.     500000.0
3  400000.0 руб./ За месяц, Залог - 400000 руб., ...   руб.     400000.0
4  225000.0 руб./ За месяц, Залог - 225000 руб., ...   руб.     225000.0

In [125]:
parts_count = df_rub["Площадь, м2"].str.split("/").str.len()
display(parts_count.value_counts().sort_index())

Площадь, м2
1     3057
2     2419
3    17868
Name: count, dtype: int64

In [126]:
display(
    df_rub.loc[
        df_rub["Площадь, м2"].str.split("/").str.len() == 1,
        ["Площадь, м2", "Адрес", "Цена"]
    ].head(15)
)

,"Площадь, м2",Адрес,Цена
5,92.0,"Москва, 1-й Смоленский переулок, 21","470000.0 руб./ За месяц, Залог - 470000 руб., ..."
14,222.2,"Москва, Филипповский переулок, 8С1","450000.0 руб./ За месяц, Залог - 450000 руб., ..."
15,225.0,"Москва, Филипповский переулок, 8С1","450000.0 руб./ За месяц, Залог - 450000 руб., ..."
17,222.0,"Москва, Филипповский переулок, 8С1","450000.0 руб./ За месяц, Залог - 450000 руб., ..."
18,150.0,"Москва, Поварская улица, 18","180000.0 руб./ За месяц, Залог - 180000 руб., ..."
22,190.0,"Москва, Малый Каковинский переулок, 6С1","590000.0 руб./ За месяц, Залог - 590000 руб., ..."
31,112.0,"Москва, улица Новый Арбат, 32","350000.0 руб./ За месяц, Залог - 350000 руб., ..."
32,91.0,"Москва, улица Новый Арбат, 32","400000.0 руб./ За месяц, Залог - 400000 руб., ..."
35,44.0,"Москва, улица Новый Арбат, 15","135000.0 руб./ За месяц, Залог - 135000 руб., ..."
37,100.0,"Москва, 1-й Смоленский переулок, 21","320000.0 руб./ За месяц, Залог - 320000 руб., ..."
38,133.3,"Москва, улица Новый Арбат, 32","400000.0 руб./ За месяц, Залог - 400000 руб., ..."
39,210.0,"Москва, переулок Плотников, 21С1","400000.0 руб./ За месяц, Залог - 400000 руб., ..."
40,180.0,"Москва, Борисоглебский переулок, 15С2","450000.0 руб./ За месяц, Залог - 450000 руб., ..."
41,165.0,"Москва, улица Новый Арбат, 27","470000.0 руб./ За месяц, Залог - 470000 руб., ..."
42,190.0,"Москва, Малый Каковинский переулок, 6С1","590000.0 руб./ За месяц, Залог - 590000 руб., ..."

In [127]:
df_rub["Общая площадь"] = (
    df_rub["Площадь, м2"]
    .str.split("/")
    .str[0]
    .astype(float)
)
display(df_rub[["Площадь, м2", "Общая площадь"]].head(10))

        Площадь, м2  Общая площадь
0        200.0/20.0          200.0
1   198.0/95.0/18.0          198.0
2   200.0/116.0/4.0          200.0
3   170.0/95.0/17.0          170.0
4     58.0/38.0/5.0           58.0
5              92.0           92.0
6  213.0/140.0/20.0          213.0
7     98.0/63.0/9.0           98.0
8   120.0/95.0/10.0          120.0
9    90.0/66.0/10.0           90.0

In [128]:
print("Пропуски в общей площади:", df_rub["Общая площадь"].isna().sum())

Пропуски в общей площади: 0

In [129]:
display(df_rub[["Площадь, м2", "Общая площадь"]].sample(10, random_state=42))

           Площадь, м2  Общая площадь
13551     14.0/8.0/3.0           14.0
7812    54.0/33.0/10.0           54.0
20768         42.0/6.0           42.0
13366   77.0/42.0/18.0           77.0
12848  180.0/85.0/38.0          180.0
247     38.0/18.0/10.0           38.0
9440     69.0/47.0/9.0           69.0
2710    45.0/30.0/10.0           45.0
3444     68.0/40.0/7.0           68.0
3429          90.0/7.0           90.0

In [130]:
df.head(0)

Empty DataFrame
Columns: [ID  объявления, Количество комнат, Тип, Метро, Адрес, Площадь, м2, Дом, Парковка, Цена, Телефоны, Описание, Ремонт, Площадь комнат, м2, Балкон, Окна, Санузел, Можно с детьми/животными, Дополнительно, Название ЖК, Серия дома, Высота потолков, м, Лифт, Мусоропровод, Ссылка на объявление, Валюта, Цена числом]
Index: []

[0 rows x 26 columns]

In [131]:
(df_rub["Цена числом"] / df_rub["Общая площадь"]).round(2)

0        2500.00
1        2525.25
2        2500.00
3        2352.94
4        3879.31
          ...
23363    1200.00
23364    1162.79
23365    1160.09
23366    1047.62
23367     633.33
Length: 23344, dtype: float64

In [132]:
df_rub["Цена за м²"] = (df_rub["Цена числом"] / df_rub["Общая площадь"]).round(2)

In [133]:
display(df_rub[["Цена числом", "Общая площадь", "Цена за м²"]].head(10))

   Цена числом  Общая площадь  Цена за м²
0     500000.0          200.0     2500.00
1     500000.0          198.0     2525.25
2     500000.0          200.0     2500.00
3     400000.0          170.0     2352.94
4     225000.0           58.0     3879.31
5     470000.0           92.0     5108.70
6     350000.0          213.0     1643.19
7     250000.0           98.0     2551.02
8     130000.0          120.0     1083.33
9     210000.0           90.0     2333.33

In [134]:
display(df_rub["Цена за м²"].describe())

count    23344.000000
mean      1187.055026
std        630.590210
min         61.510000
25%        833.330000
50%       1000.000000
75%       1333.330000
max      12285.710000
Name: Цена за м², dtype: float64

In [135]:
print(df_rub.columns.tolist())

['ID  объявления', 'Количество комнат', 'Тип', 'Метро', 'Адрес', 'Площадь, м2', 'Дом', 'Парковка', 'Цена', 'Телефоны', 'Описание', 'Ремонт', 'Площадь комнат, м2', 'Балкон', 'Окна', 'Санузел', 'Можно с детьми/животными', 'Дополнительно', 'Название ЖК', 'Серия дома', 'Высота потолков, м', 'Лифт', 'Мусоропровод', 'Ссылка на объявление', 'Валюта', 'Цена числом', 'Общая площадь', 'Цена за м²']

In [136]:
display(
    df_rub.nsmallest(10, "Цена за м²")[
        ["ID  объявления", "Адрес", "Цена числом", "Общая площадь", "Цена за м²"]
    ]
)

,ID объявления,Адрес,Цена числом,Общая площадь,Цена за м²
21396,274626772,"Санкт-Петербург, Двинская улица, 16К3",14000.0,227.6,61.51
2522,274633188,"Москва, Неманский проезд, 1к1",60000.0,775.0,77.42
7109,274475586,"Москва, улица Амундсена, 1К2",45000.0,560.0,80.36
13870,274946067,"Москва, Хорошевское шоссе, 12к1",76000.0,550.0,138.18
1036,271660240,"Санкт-Петербург, проспект Энтузиастов, 31к3",25000.0,100.3,249.25
22657,274969842,"Санкт-Петербург, пос. Шушары, Славянка тер., у...",21000.0,78.0,269.23
22640,274695496,"Санкт-Петербург, пос. Шушары, Славянка тер., у...",22000.0,79.0,278.48
10881,274568678,"Санкт-Петербург, Колпино, Октябрьская улица, 7...",16000.0,56.0,285.71
10910,274882953,"Санкт-Петербург, пос. Металлострой, Центральна...",20000.0,70.0,285.71
10912,269580730,"Санкт-Петербург, Колпино, Загородная улица, 48...",20000.0,70.0,285.71

In [137]:
display(
    df_rub.nlargest(10, "Цена за м²")[
        ["ID  объявления", "Адрес", "Цена числом", "Общая площадь", "Цена за м²"]
    ]
)

,ID объявления,Адрес,Цена числом,Общая площадь,Цена за м²
2974,272551392,"Краснодарский край, Сочи, Курортный проспект, ...",1290000.0,105.0,12285.71
17639,262610649,"Москва, Ордынский тупик, 4А",1500000.0,158.0,9493.67
20498,273673272,"Москва, Зеленый проспект, 22",700000.0,74.0,9459.46
17593,271305685,"Москва, 3-й Кадашевский переулок, 7-9С1",1500000.0,165.0,9090.91
4675,273526190,"Москва, улица Охотный Ряд, 2",1050000.0,116.0,9051.72
3007,271263257,"Краснодарский край, Сочи, Курортный проспект, ...",1700000.0,200.0,8500.00
4715,273806652,"Москва, Бутиковский переулок, 5",3000000.0,358.0,8379.89
4766,274270529,"Москва, Бутиковский переулок, 5",3000000.0,358.0,8379.89
14237,268954105,"Москва, Бутиковский переулок, 5",3000000.0,358.0,8379.89
14238,268953362,"Москва, Бутиковский переулок, 5",3000000.0,358.0,8379.89

In [138]:
display(
    df_rub.loc[
        df_rub["ID  объявления"] == 272551392,
        ["ID  объявления", "Цена", "Площадь, м2", "Описание"]
    ].T
)

                                                             2974
ID  объявления                                          272551392
Цена            1290000.0 руб./ За месяц, Срок аренды - На нес...
Площадь, м2                                                 105.0
Описание        Люксовый апартамент с дизайнерским ремонтом дл...

In [139]:
display(
    df_rub.nsmallest(10, "Общая площадь")[
        ["ID  объявления", "Адрес", "Цена числом", "Общая площадь", "Площадь, м2"]
    ]
)

,ID объявления,Адрес,Цена числом,Общая площадь,"Площадь, м2"
15105,275003684,"Москва, улица Кашенкин Луг, 11",38000.0,7.0,7.0
1556,274944164,"Москва, Цимлянская улица, 3к3",22000.0,10.0,10.0/7.0/2.0
6313,274414358,"Москва, Дегунинская улица, 1К3",30000.0,11.0,11.0/8.0/2.0
11245,239966898,"Москва, Ярославское шоссе, 124",20000.0,11.0,11.0/8.0
5230,261704536,"Москва, Клинская улица, 4К2",27000.0,12.0,12.0
6282,228524680,"Москва, Дегунинская улица, 1К3",28000.0,12.0,12.0
9559,263627242,"Москва, улица Каховка, 26",30000.0,12.0,12.0/7.0/2.0
16804,274043283,"Москва, Байкальская улица, 26/10",23000.0,12.0,12.0/9.0/3.0
17119,268870682,"Москва, Подъемная улица, 14С37",35000.0,12.0,12.0/7.0/3.0
23208,274517168,"Москва, Солнцевский проспект, 9К2, ш. Боровско...",30000.0,12.0,12.0/6.0/3.0

In [140]:
display(
    df_rub.loc[
        df_rub["ID  объявления"] == 275003684,
        ["ID  объявления", "Цена", "Площадь, м2", "Описание"]
    ].T
)

                                                            15105
ID  объявления                                          275003684
Цена            38000.0 руб./ За месяц, Залог - 38000 руб., Ко...
Площадь, м2                                                   7.0
Описание        Сдаю на долгий срок квартиру на втором этаже, ...

In [141]:
(df_rub["Общая площадь"] < 15).sum()

np.int64(47)

In [142]:
display(
    df_rub.loc[
        df_rub["Общая площадь"] < 15,
        ["ID  объявления", "Адрес", "Цена числом", "Общая площадь", "Площадь, м2"]
    ].sort_values("Общая площадь")
)

,ID объявления,Адрес,Цена числом,Общая площадь,"Площадь, м2"
15105,275003684,"Москва, улица Кашенкин Луг, 11",38000.0,7.0,7.0
1556,274944164,"Москва, Цимлянская улица, 3к3",22000.0,10.0,10.0/7.0/2.0
11245,239966898,"Москва, Ярославское шоссе, 124",20000.0,11.0,11.0/8.0
6313,274414358,"Москва, Дегунинская улица, 1К3",30000.0,11.0,11.0/8.0/2.0
5230,261704536,"Москва, Клинская улица, 4К2",27000.0,12.0,12.0
9559,263627242,"Москва, улица Каховка, 26",30000.0,12.0,12.0/7.0/2.0
6282,228524680,"Москва, Дегунинская улица, 1К3",28000.0,12.0,12.0
16804,274043283,"Москва, Байкальская улица, 26/10",23000.0,12.0,12.0/9.0/3.0
17119,268870682,"Москва, Подъемная улица, 14С37",35000.0,12.0,12.0/7.0/3.0
23208,274517168,"Москва, Солнцевский проспект, 9К2, ш. Боровско...",30000.0,12.0,12.0/6.0/3.0
19729,266990420,"Санкт-Петербург, Большой Сампсониевский проспе...",30000.0,12.3,12.3
3960,236789779,"Москва, 9-я Парковая улица, 66К2",26000.0,13.0,13.0/8.0/3.0
7350,274935565,"Москва, Яхромская улица, 3",37500.0,13.0,13.0
1829,249819541,"Москва, Волжский бульвар, 41К4",23000.0,13.0,13.0/9.0/3.0
2683,274875441,"Москва, Фестивальная улица, 52К1",30000.0,13.0,13.0
5208,273645696,"Москва, Клинская улица, 4К2",28000.0,13.0,13.0
17116,274902638,"Москва, Подъемная улица, 14С37",30000.0,13.0,13.0/5.0/4.0
17203,266018445,"Москва, Подъемная улица, 14С25",48000.0,13.0,13.0/10.0/1.0
19970,274453462,"Санкт-Петербург, проспект Средний Васильевског...",25000.0,13.0,13.0/10.0/2.0
17205,268824507,"Москва, Подъемная улица, 14С25",25000.0,13.0,13.0/11.0
15010,272679813,"Москва, 1-й Грайвороновский проезд, 2А",29000.0,13.0,13.0/10.0/2.0
21534,274357920,"Москва, Минусинская улица, 11",30000.0,13.0,13.0
13546,274057159,"Москва, проспект Вернадского, 41С1",30000.0,13.3,13.3/13.3
11246,169086145,"Москва, Ярославское шоссе, 124",21000.0,14.0,14.0/8.0
13551,273591120,"Москва, проспект Вернадского, 41С1",45000.0,14.0,14.0/8.0/3.0
7064,268332264,"Москва, проезд Серебрякова, 11к1",31990.0,14.0,14.0
4410,274772501,"Москва, улица Буракова, 1К1",26000.0,14.0,14.0/9.0/3.0
4352,274829585,"Москва, улица Буракова, 1К1",28000.0,14.0,14.0/9.0/3.0
2690,266029609,"Москва, Фестивальная улица, 52",30000.0,14.0,14.0/8.0/4.0
11466,273626820,"Москва, бульвар Генерала Карбышева, 19К5",28000.0,14.0,14.0/11.0
2720,274259876,"Москва, Автомоторная улица, 3К1",20000.0,14.0,14.0/8.0/4.0
3917,273791617,"Москва, 9-я Парковая улица, 66К2",27000.0,14.0,14.0/9.0/3.0
8389,268820958,"Москва, Нахимовский проспект, 2",46000.0,14.0,14.0/14.0
17170,267748891,"Москва, Подъемная улица, 14С25",33000.0,14.0,14.0/10.0
16249,273570611,"Санкт-Петербург, Рузовская улица, 33",15500.0,14.0,14.0
15095,273893047,"Москва, Гостиничный проезд, 8К1",30000.0,14.0,14.0/3.0
14963,273490097,"Москва, Волжский бульвар, 8К3",28000.0,14.0,14.0/7.0/3.0
13573,273646879,"Москва, проспект Вернадского, 41",35000.0,14.0,14.0
13547,274294401,"Москва, проспект Вернадского, 41С1",35000.0,14.0,14.0/8.0
15052,274064070,"Москва, Волжский бульвар, 8К3",28000.0,14.0,14.0/12.0
23209,272632468,"Москва, Солнцевский проспект, 9К2, ш. Боровско...",30000.0,14.0,14.0/7.0/4.0
17113,272772540,"Москва, Подъемная улица, 14С37",26000.0,14.0,14.0/10.0
17121,274039104,"Москва, Подъемная улица, 14С44",35000.0,14.4,14.4/12.0/1.5
5606,272653359,"Москва, 1-й Грайвороновский проезд, 2А",30000.0,14.5,14.5/10.0/2.0
13606,273310976,"Москва, проспект Вернадского, 41С1",50000.0,14.5,14.5/10.0/2.0
13608,274584577,"Москва, проспект Вернадского, 41С1",50000.0,14.5,14.5/10.0/4.5
19732,266610700,"Санкт-Петербург, Большой Сампсониевский проспе...",33000.0,14.8,14.8/2.1

In [143]:
df_rub["ID  объявления"].duplicated().sum()

np.int64(0)

In [144]:
display(df_rub[["Цена числом", "Общая площадь", "Цена за м²"]].isna().sum())

Цена числом      0
Общая площадь    0
Цена за м²       0
dtype: int64

In [145]:
print("Цена меньше или равна нулю:", (df_rub["Цена числом"] <= 0).sum())
print("Площадь меньше или равна нулю:", (df_rub["Общая площадь"] <= 0).sum())
print("Цена за м² меньше или равна нулю:", (df_rub["Цена за м²"] <= 0).sum())

Цена меньше или равна нулю: 0
Площадь меньше или равна нулю: 0
Цена за м² меньше или равна нулю: 0

In [146]:
df_rub.isna().sum()

ID  объявления                  0
Количество комнат            1041
Тип                             0
Метро                        1314
Адрес                           0
Площадь, м2                     0
Дом                             0
Парковка                    13405
Цена                            0
Телефоны                        0
Описание                        0
Ремонт                       2751
Площадь комнат, м2           8898
Балкон                       7970
Окна                         6608
Санузел                      2670
Можно с детьми/животными     6092
Дополнительно                 356
Название ЖК                 17508
Серия дома                  21184
Высота потолков, м          12148
Лифт                         5496
Мусоропровод                10505
Ссылка на объявление            0
Валюта                          0
Цена числом                     0
Общая площадь                   0
Цена за м²                      0
dtype: int64

In [147]:
missing = df_rub.isna().sum()

In [148]:
missing_table = pd.DataFrame({
    "Пропуски": missing,
    "Процент пропусков": missing_percent
})

In [149]:
display(
    missing_table[missing_table["Пропуски"] > 0]
    .sort_values("Процент пропусков", ascending=False)
)

                          Пропуски  Процент пропусков
Серия дома                   21184              90.74
Название ЖК                  17508              74.97
Парковка                     13405              57.42
Высота потолков, м           12148              52.05
Мусоропровод                 10505              45.03
Площадь комнат, м2            8898              38.13
Балкон                        7970              34.14
Окна                          6608              28.30
Можно с детьми/животными      6092              26.09
Лифт                          5496              23.54
Ремонт                        2751              11.79
Санузел                       2670              11.43
Метро                         1314               5.63
Количество комнат             1041               4.45
Дополнительно                  356               1.53

In [150]:
df_rub.to_csv(
    "../data_processed/real_estate_processed.csv",
    index=False
)

In [151]:
pd.read_csv("../data_processed/real_estate_processed.csv")

,ID объявления,Количество комнат,Тип,Метро,Адрес,"Площадь, м2",Дом,Парковка,Цена,Телефоны,...,Название ЖК,Серия дома,"Высота потолков, м",Лифт,Мусоропровод,Ссылка на объявление,Валюта,Цена числом,Общая площадь,Цена за м²
0,271271157,4,Квартира,м. Смоленская (9 мин пешком),"Москва, улица Новый Арбат, 27",200.0/20.0,"5/16, Монолитный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",+79166369231,...,"Новый Арбат, 2010",NaN,3.00,"Пасс (4), Груз (1)",Да,https://www.cian.ru/rent/flat/271271157,руб.,500000.0,200.0,2500.00
1,271634126,4,Квартира,м. Смоленская (8 мин пешком),"Москва, улица Новый Арбат, 27",198.0/95.0/18.0,"5/16, Монолитно-кирпичный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",+79850608590,...,Новый Арбат,NaN,3.50,"Пасс (1), Груз (1)",Нет,https://www.cian.ru/rent/flat/271634126,руб.,500000.0,198.0,2525.25
2,271173086,"4, Оба варианта",Квартира,м. Смоленская (7 мин пешком),"Москва, улица Новый Арбат, 27",200.0/116.0/4.0,5/16,подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...","+79672086536, +79099269384",...,Новый Арбат,NaN,3.20,Пасс (1),NaN,https://www.cian.ru/rent/flat/271173086,руб.,500000.0,200.0,2500.00
3,272197456,"4, Оба варианта",Квартира,м. Смоленская (3 мин пешком),"Москва, переулок Плотников, 21С1",170.0/95.0/17.0,5/6,подземная,"400000.0 руб./ За месяц, Залог - 400000 руб., ...","+79660342340, +79099269384",...,NaN,NaN,3.20,Пасс (1),NaN,https://www.cian.ru/rent/flat/272197456,руб.,400000.0,170.0,2352.94
4,273614615,2,Квартира,м. Арбатская (7 мин пешком),"Москва, улица Новый Арбат, 15",58.0/38.0/5.0,"12/26, Панельный",NaN,"225000.0 руб./ За месяц, Залог - 225000 руб., ...",+79852432860,...,The Book,NaN,3.90,"Пасс (1), Груз (1)",Да,https://www.cian.ru/rent/flat/273614615,руб.,225000.0,58.0,3879.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23339,215565511,NaN,Квартира,м. Говорово (8 мин пешком),"Москва, Боровское шоссе, 2к7, ш. Боровское (3 ...",35.0/16.4/8.0,10/14,NaN,"42000.0 руб./ За месяц, Залог - 42000 руб., Ко...",+79154383401,...,Мещерский лес,NaN,NaN,"Пасс (1), Груз (1)",NaN,https://www.cian.ru/rent/flat/215565511,руб.,42000.0,35.0,1200.00
23340,274654844,1,Квартира,м. Солнцево (7 мин пешком),"Москва, Производственная улица, 8к1, ш. Боровс...",38.7/16.5/11.0,"5/18, Монолитный",NaN,"45000.0 руб./ За месяц, Залог - 45000 руб., Ко...",+79151173402,...,Лучи,NaN,NaN,"Пасс (1), Груз (1)",NaN,https://www.cian.ru/rent/flat/274654844,руб.,45000.0,38.7,1162.79
23341,268679909,"2, Оба варианта",Квартира,м. Солнцево (6 мин пешком),"Москва, Боровский проезд, 11",43.1,"5/5, Кирпичный",NaN,"50000.0 руб./ За месяц, Залог - 50000 руб., Ко...",+79653825192,...,NaN,NaN,NaN,NaN,NaN,https://www.cian.ru/rent/flat/268679909,руб.,50000.0,43.1,1160.09
23342,274807525,2,Квартира,м. Солнцево (11 мин пешком),"Москва, улица Богданова, 6к1, ш. Боровское (3 ...",52.5/10.0,"8/23, Монолитный",наземная,"55000.0 руб./ За месяц, Залог - 50000 руб., Ко...",+79660611965,...,NaN,NaN,2.65,Пасс (3),Да,https://www.cian.ru/rent/flat/274807525,руб.,55000.0,52.5,1047.62
23343,274672243,"2, Оба варианта",Квартира,м. Говорово (10 мин пешком),"Москва, улица Богданова, 2к1, ш. Боровское (3 ...",90.0/48.2/15.5,"6/23, Панельный",NaN,"57000.0 руб./ За месяц, Залог - 60000 руб., Ко...",+79623641533,...,NaN,NaN,NaN,Пасс (3),Да,https://www.cian.ru/rent/flat/274672243,руб.,57000.0,90.0,633.33

In [154]:
df_check = pd.read_csv("../data_processed/real_estate_processed.csv")

In [155]:
print("Размер сохранённого файла:", df_check.shape)
print("Количество дубликатов:", df_check.duplicated().sum())
print("Количество пропусков в цене за м²:", df_check["Цена за м²"].isna().sum())

Размер сохранённого файла: (23344, 28)
Количество дубликатов: 0
Количество пропусков в цене за м²: 0