In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("../data/real_estate_agency.csv")

In [5]:
print(f"Количество строк = {df.shape[0]}")
print(f"Количество стобцов = {df.shape[1]}")
display(df.head())
df.info()

Количество строк = 23368
Количество стобцов = 25

,Unnamed: 0,ID объявления,Количество комнат,Тип,Метро,Адрес,"Площадь, м2",Дом,Парковка,Цена,...,Окна,Санузел,Можно с детьми/животными,Дополнительно,Название ЖК,Серия дома,"Высота потолков, м",Лифт,Мусоропровод,Ссылка на объявление
0,0,271271157,4,Квартира,м. Смоленская (9 мин пешком),"Москва, улица Новый Арбат, 27",200.0/20.0,"5/16, Монолитный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",...,NaN,NaN,"Можно с детьми, Можно с животными","Мебель в комнатах, Мебель на кухне, Ванна, Душ...","Новый Арбат, 2010",NaN,3.0,"Пасс (4), Груз (1)",Да,https://www.cian.ru/rent/flat/271271157
1,1,271634126,4,Квартира,м. Смоленская (8 мин пешком),"Москва, улица Новый Арбат, 27",198.0/95.0/18.0,"5/16, Монолитно-кирпичный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",...,На улицу и двор,"Совмещенный (2), Раздельный (1)",Можно с детьми,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",Новый Арбат,NaN,3.5,"Пасс (1), Груз (1)",Нет,https://www.cian.ru/rent/flat/271634126
2,2,271173086,"4, Оба варианта",Квартира,м. Смоленская (7 мин пешком),"Москва, улица Новый Арбат, 27",200.0/116.0/4.0,5/16,подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",...,На улицу и двор,Совмещенный (3),Можно с детьми,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",Новый Арбат,NaN,3.2,Пасс (1),NaN,https://www.cian.ru/rent/flat/271173086
3,3,272197456,"4, Оба варианта",Квартира,м. Смоленская (3 мин пешком),"Москва, переулок Плотников, 21С1",170.0/95.0/17.0,5/6,подземная,"400000.0 руб./ За месяц, Залог - 400000 руб., ...",...,На улицу и двор,Совмещенный (3),Можно с животными,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",NaN,NaN,3.2,Пасс (1),NaN,https://www.cian.ru/rent/flat/272197456
4,4,273614615,2,Квартира,м. Арбатская (7 мин пешком),"Москва, улица Новый Арбат, 15",58.0/38.0/5.0,"12/26, Панельный",NaN,"225000.0 руб./ За месяц, Залог - 225000 руб., ...",...,На улицу и двор,Совмещенный (2),NaN,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",The Book,NaN,3.9,"Пасс (1), Груз (1)",Да,https://www.cian.ru/rent/flat/273614615

<class 'pandas.DataFrame'>
RangeIndex: 23368 entries, 0 to 23367
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                23368 non-null  int64
 1   ID  объявления            23368 non-null  int64
 2   Количество комнат         22327 non-null  str
 3   Тип                       23368 non-null  str
 4   Метро                     22053 non-null  str
 5   Адрес                     23368 non-null  str
 6   Площадь, м2               23368 non-null  str
 7   Дом                       23368 non-null  str
 8   Парковка                  9951 non-null   str
 9   Цена                      23368 non-null  str
 10  Телефоны                  23368 non-null  str
 11  Описание                  23368 non-null  str
 12  Ремонт                    20613 non-null  str
 13  Площадь комнат, м2        14458 non-null  str
 14  Балкон                    15390 non-null  str
 15  Окна                      16755 non-null  str
 16  Санузел                   20696 non-null  str
 17  Можно с детьми/животными  17272 non-null  str
 18  Дополнительно             23011 non-null  str
 19  Название ЖК               5848 non-null   str
 20  Серия дома                2163 non-null   str
 21  Высота потолков, м        11206 non-null  float64
 22  Лифт                      17868 non-null  str
 23  Мусоропровод              12846 non-null  str
 24  Ссылка на объявление      23368 non-null  str
dtypes: float64(1), int64(2), str(22)
memory usage: 42.5 MB

In [6]:
df = df.drop(columns=["Unnamed: 0"])

In [7]:
print(f"Количество строк: {df.shape[0]}")
print(f"Количество столбцов: {df.shape[1]}")

Количество строк: 23368
Количество столбцов: 24

In [8]:
print(f"Количество дубликатов: {df.duplicated().sum()}")

Количество дубликатов: 0

In [9]:
df.isna().sum()

ID  объявления                  0
Количество комнат            1041
Тип                             0
Метро                        1315
Адрес                           0
Площадь, м2                     0
Дом                             0
Парковка                    13417
Цена                            0
Телефоны                        0
Описание                        0
Ремонт                       2755
Площадь комнат, м2           8910
Балкон                       7978
Окна                         6613
Санузел                      2672
Можно с детьми/животными     6096
Дополнительно                 357
Название ЖК                 17520
Серия дома                  21205
Высота потолков, м          12162
Лифт                         5500
Мусоропровод                10522
Ссылка на объявление            0
dtype: int64

In [10]:
missing = df.isna().sum()

In [11]:
missing[missing > 0]

Количество комнат            1041
Метро                        1315
Парковка                    13417
Ремонт                       2755
Площадь комнат, м2           8910
Балкон                       7978
Окна                         6613
Санузел                      2672
Можно с детьми/животными     6096
Дополнительно                 357
Название ЖК                 17520
Серия дома                  21205
Высота потолков, м          12162
Лифт                         5500
Мусоропровод                10522
dtype: int64

In [12]:
missing = missing[missing > 0]

In [13]:
((missing / len(df)) * 100).round(2)

Количество комнат            4.45
Метро                        5.63
Парковка                    57.42
Ремонт                      11.79
Площадь комнат, м2          38.13
Балкон                      34.14
Окна                        28.30
Санузел                     11.43
Можно с детьми/животными    26.09
Дополнительно                1.53
Название ЖК                 74.97
Серия дома                  90.74
Высота потолков, м          52.05
Лифт                        23.54
Мусоропровод                45.03
dtype: float64

In [14]:
missing_percent = ((missing / len(df)) * 100).round(2)

In [15]:
missing_df = pd.DataFrame({
    "Пропусков": missing,
    "Пропусков, %": missing_percent
})

In [16]:
missing_df.sort_values("Пропусков", ascending=False)

                          Пропусков  Пропусков, %
Серия дома                    21205         90.74
Название ЖК                   17520         74.97
Парковка                      13417         57.42
Высота потолков, м            12162         52.05
Мусоропровод                  10522         45.03
Площадь комнат, м2             8910         38.13
Балкон                         7978         34.14
Окна                           6613         28.30
Можно с детьми/животными       6096         26.09
Лифт                           5500         23.54
Ремонт                         2755         11.79
Санузел                        2672         11.43
Метро                          1315          5.63
Количество комнат              1041          4.45
Дополнительно                   357          1.53

In [17]:
missing_df = missing_df.sort_values("Пропусков", ascending=False)

In [18]:
display(missing_df)

                          Пропусков  Пропусков, %
Серия дома                    21205         90.74
Название ЖК                   17520         74.97
Парковка                      13417         57.42
Высота потолков, м            12162         52.05
Мусоропровод                  10522         45.03
Площадь комнат, м2             8910         38.13
Балкон                         7978         34.14
Окна                           6613         28.30
Можно с детьми/животными       6096         26.09
Лифт                           5500         23.54
Ремонт                         2755         11.79
Санузел                        2672         11.43
Метро                          1315          5.63
Количество комнат              1041          4.45
Дополнительно                   357          1.53

In [19]:
display(df.dtypes)

ID  объявления                int64
Количество комнат               str
Тип                             str
Метро                           str
Адрес                           str
Площадь, м2                     str
Дом                             str
Парковка                        str
Цена                            str
Телефоны                        str
Описание                        str
Ремонт                          str
Площадь комнат, м2              str
Балкон                          str
Окна                            str
Санузел                         str
Можно с детьми/животными        str
Дополнительно                   str
Название ЖК                     str
Серия дома                      str
Высота потолков, м          float64
Лифт                            str
Мусоропровод                    str
Ссылка на объявление            str
dtype: object

In [20]:
df["Валюта"] = df["Цена"]

In [21]:
df.head(0)

Empty DataFrame
Columns: [ID  объявления, Количество комнат, Тип, Метро, Адрес, Площадь, м2, Дом, Парковка, Цена, Телефоны, Описание, Ремонт, Площадь комнат, м2, Балкон, Окна, Санузел, Можно с детьми/животными, Дополнительно, Название ЖК, Серия дома, Высота потолков, м, Лифт, Мусоропровод, Ссылка на объявление, Валюта]
Index: []

[0 rows x 25 columns]

In [22]:
display(df["Цена"].str.extract(r"^[\d.]+\s*([^\s/]+)")[0].value_counts(dropna=False))

0
руб.    23344
$          14
€          10
Name: count, dtype: int64

In [23]:
display(
    df["Цена"]
    .str.extract(r"^[\d.]+\s*([^\s/]+)")[0]
    .value_counts(dropna=False)
    .head(10000)
)

0
руб.    23344
$          14
€          10
Name: count, dtype: int64

In [24]:
df["Валюта"] = df["Цена"].str.extract(r"^[\d.]+\s*([^\s/]+)")[0]

In [25]:
df["Цена числом"] = df["Цена"].str.extract(r"^([\d.]+)")[0].astype(float)

In [26]:
df.head(0)

Empty DataFrame
Columns: [ID  объявления, Количество комнат, Тип, Метро, Адрес, Площадь, м2, Дом, Парковка, Цена, Телефоны, Описание, Ремонт, Площадь комнат, м2, Балкон, Окна, Санузел, Можно с детьми/животными, Дополнительно, Название ЖК, Серия дома, Высота потолков, м, Лифт, Мусоропровод, Ссылка на объявление, Валюта, Цена числом]
Index: []

[0 rows x 26 columns]

In [27]:
display(df[["Цена", "Валюта", "Цена числом"]].head(10))

                                                Цена Валюта  Цена числом
0  500000.0 руб./ За месяц, Залог - 500000 руб., ...   руб.     500000.0
1  500000.0 руб./ За месяц, Залог - 500000 руб., ...   руб.     500000.0
2  500000.0 руб./ За месяц, Залог - 500000 руб., ...   руб.     500000.0
3  400000.0 руб./ За месяц, Залог - 400000 руб., ...   руб.     400000.0
4  225000.0 руб./ За месяц, Залог - 225000 руб., ...   руб.     225000.0
5  470000.0 руб./ За месяц, Залог - 470000 руб., ...   руб.     470000.0
6  350000.0 руб./ За месяц, Залог - 350000 руб., ...   руб.     350000.0
7  250000.0 руб./ За месяц, Залог - 250000 руб., ...   руб.     250000.0
8  130000.0 руб./ За месяц, Залог - 130000 руб., ...   руб.     130000.0
9  210000.0 руб./ За месяц, Залог - 210000 руб., ...   руб.     210000.0

In [28]:
display(df["Валюта"].value_counts(dropna=False))

Валюта
руб.    23344
$          14
€          10
Name: count, dtype: int64

In [29]:
print("Пропуски в цене:", df["Цена числом"].isna().sum())
print("Пропуски в валюте:", df["Валюта"].isna().sum())

Пропуски в цене: 0
Пропуски в валюте: 0

In [30]:
df_rub = df[df["Валюта"] == "руб."].copy()

In [31]:
print("Количество рублёвых объявлений:", len(df_rub))

Количество рублёвых объявлений: 23344

In [32]:
display(df_rub[["Цена", "Валюта", "Цена числом"]].head())

                                                Цена Валюта  Цена числом
0  500000.0 руб./ За месяц, Залог - 500000 руб., ...   руб.     500000.0
1  500000.0 руб./ За месяц, Залог - 500000 руб., ...   руб.     500000.0
2  500000.0 руб./ За месяц, Залог - 500000 руб., ...   руб.     500000.0
3  400000.0 руб./ За месяц, Залог - 400000 руб., ...   руб.     400000.0
4  225000.0 руб./ За месяц, Залог - 225000 руб., ...   руб.     225000.0

In [33]:
parts_count = df_rub["Площадь, м2"].str.split("/").str.len()
display(parts_count.value_counts().sort_index())

Площадь, м2
1     3057
2     2419
3    17868
Name: count, dtype: int64

In [34]:
display(
    df_rub.loc[
        df_rub["Площадь, м2"].str.split("/").str.len() == 1,
        ["Площадь, м2", "Адрес", "Цена"]
    ].head(15)
)

,"Площадь, м2",Адрес,Цена
5,92.0,"Москва, 1-й Смоленский переулок, 21","470000.0 руб./ За месяц, Залог - 470000 руб., ..."
14,222.2,"Москва, Филипповский переулок, 8С1","450000.0 руб./ За месяц, Залог - 450000 руб., ..."
15,225.0,"Москва, Филипповский переулок, 8С1","450000.0 руб./ За месяц, Залог - 450000 руб., ..."
17,222.0,"Москва, Филипповский переулок, 8С1","450000.0 руб./ За месяц, Залог - 450000 руб., ..."
18,150.0,"Москва, Поварская улица, 18","180000.0 руб./ За месяц, Залог - 180000 руб., ..."
22,190.0,"Москва, Малый Каковинский переулок, 6С1","590000.0 руб./ За месяц, Залог - 590000 руб., ..."
31,112.0,"Москва, улица Новый Арбат, 32","350000.0 руб./ За месяц, Залог - 350000 руб., ..."
32,91.0,"Москва, улица Новый Арбат, 32","400000.0 руб./ За месяц, Залог - 400000 руб., ..."
35,44.0,"Москва, улица Новый Арбат, 15","135000.0 руб./ За месяц, Залог - 135000 руб., ..."
37,100.0,"Москва, 1-й Смоленский переулок, 21","320000.0 руб./ За месяц, Залог - 320000 руб., ..."
38,133.3,"Москва, улица Новый Арбат, 32","400000.0 руб./ За месяц, Залог - 400000 руб., ..."
39,210.0,"Москва, переулок Плотников, 21С1","400000.0 руб./ За месяц, Залог - 400000 руб., ..."
40,180.0,"Москва, Борисоглебский переулок, 15С2","450000.0 руб./ За месяц, Залог - 450000 руб., ..."
41,165.0,"Москва, улица Новый Арбат, 27","470000.0 руб./ За месяц, Залог - 470000 руб., ..."
42,190.0,"Москва, Малый Каковинский переулок, 6С1","590000.0 руб./ За месяц, Залог - 590000 руб., ..."

In [35]:
df_rub["Общая площадь"] = (
    df_rub["Площадь, м2"]
    .str.split("/")
    .str[0]
    .astype(float)
)
display(df_rub[["Площадь, м2", "Общая площадь"]].head(10))

        Площадь, м2  Общая площадь
0        200.0/20.0          200.0
1   198.0/95.0/18.0          198.0
2   200.0/116.0/4.0          200.0
3   170.0/95.0/17.0          170.0
4     58.0/38.0/5.0           58.0
5              92.0           92.0
6  213.0/140.0/20.0          213.0
7     98.0/63.0/9.0           98.0
8   120.0/95.0/10.0          120.0
9    90.0/66.0/10.0           90.0

In [36]:
print("Пропуски в общей площади:", df_rub["Общая площадь"].isna().sum())

Пропуски в общей площади: 0

In [37]:
display(df_rub[["Площадь, м2", "Общая площадь"]].sample(10, random_state=42))

           Площадь, м2  Общая площадь
13551     14.0/8.0/3.0           14.0
7812    54.0/33.0/10.0           54.0
20768         42.0/6.0           42.0
13366   77.0/42.0/18.0           77.0
12848  180.0/85.0/38.0          180.0
247     38.0/18.0/10.0           38.0
9440     69.0/47.0/9.0           69.0
2710    45.0/30.0/10.0           45.0
3444     68.0/40.0/7.0           68.0
3429          90.0/7.0           90.0

In [38]:
df.head(0)

Empty DataFrame
Columns: [ID  объявления, Количество комнат, Тип, Метро, Адрес, Площадь, м2, Дом, Парковка, Цена, Телефоны, Описание, Ремонт, Площадь комнат, м2, Балкон, Окна, Санузел, Можно с детьми/животными, Дополнительно, Название ЖК, Серия дома, Высота потолков, м, Лифт, Мусоропровод, Ссылка на объявление, Валюта, Цена числом]
Index: []

[0 rows x 26 columns]

In [39]:
(df_rub["Цена числом"] / df_rub["Общая площадь"]).round(2)

0        2500.00
1        2525.25
2        2500.00
3        2352.94
4        3879.31
          ...
23363    1200.00
23364    1162.79
23365    1160.09
23366    1047.62
23367     633.33
Length: 23344, dtype: float64

In [40]:
df_rub["Цена за м²"] = (df_rub["Цена числом"] / df_rub["Общая площадь"]).round(2)

In [41]:
display(df_rub[["Цена числом", "Общая площадь", "Цена за м²"]].head(10))

   Цена числом  Общая площадь  Цена за м²
0     500000.0          200.0     2500.00
1     500000.0          198.0     2525.25
2     500000.0          200.0     2500.00
3     400000.0          170.0     2352.94
4     225000.0           58.0     3879.31
5     470000.0           92.0     5108.70
6     350000.0          213.0     1643.19
7     250000.0           98.0     2551.02
8     130000.0          120.0     1083.33
9     210000.0           90.0     2333.33

In [42]:
display(df_rub["Цена за м²"].describe())

count    23344.000000
mean      1187.055026
std        630.590210
min         61.510000
25%        833.330000
50%       1000.000000
75%       1333.330000
max      12285.710000
Name: Цена за м², dtype: float64

In [43]:
print(df_rub.columns.tolist())

['ID  объявления', 'Количество комнат', 'Тип', 'Метро', 'Адрес', 'Площадь, м2', 'Дом', 'Парковка', 'Цена', 'Телефоны', 'Описание', 'Ремонт', 'Площадь комнат, м2', 'Балкон', 'Окна', 'Санузел', 'Можно с детьми/животными', 'Дополнительно', 'Название ЖК', 'Серия дома', 'Высота потолков, м', 'Лифт', 'Мусоропровод', 'Ссылка на объявление', 'Валюта', 'Цена числом', 'Общая площадь', 'Цена за м²']

In [44]:
display(
    df_rub.nsmallest(10, "Цена за м²")[
        ["ID  объявления", "Адрес", "Цена числом", "Общая площадь", "Цена за м²"]
    ]
)

,ID объявления,Адрес,Цена числом,Общая площадь,Цена за м²
21396,274626772,"Санкт-Петербург, Двинская улица, 16К3",14000.0,227.6,61.51
2522,274633188,"Москва, Неманский проезд, 1к1",60000.0,775.0,77.42
7109,274475586,"Москва, улица Амундсена, 1К2",45000.0,560.0,80.36
13870,274946067,"Москва, Хорошевское шоссе, 12к1",76000.0,550.0,138.18
1036,271660240,"Санкт-Петербург, проспект Энтузиастов, 31к3",25000.0,100.3,249.25
22657,274969842,"Санкт-Петербург, пос. Шушары, Славянка тер., у...",21000.0,78.0,269.23
22640,274695496,"Санкт-Петербург, пос. Шушары, Славянка тер., у...",22000.0,79.0,278.48
10881,274568678,"Санкт-Петербург, Колпино, Октябрьская улица, 7...",16000.0,56.0,285.71
10910,274882953,"Санкт-Петербург, пос. Металлострой, Центральна...",20000.0,70.0,285.71
10912,269580730,"Санкт-Петербург, Колпино, Загородная улица, 48...",20000.0,70.0,285.71

In [45]:
display(
    df_rub.nlargest(10, "Цена за м²")[
        ["ID  объявления", "Адрес", "Цена числом", "Общая площадь", "Цена за м²"]
    ]
)

,ID объявления,Адрес,Цена числом,Общая площадь,Цена за м²
2974,272551392,"Краснодарский край, Сочи, Курортный проспект, ...",1290000.0,105.0,12285.71
17639,262610649,"Москва, Ордынский тупик, 4А",1500000.0,158.0,9493.67
20498,273673272,"Москва, Зеленый проспект, 22",700000.0,74.0,9459.46
17593,271305685,"Москва, 3-й Кадашевский переулок, 7-9С1",1500000.0,165.0,9090.91
4675,273526190,"Москва, улица Охотный Ряд, 2",1050000.0,116.0,9051.72
3007,271263257,"Краснодарский край, Сочи, Курортный проспект, ...",1700000.0,200.0,8500.00
4715,273806652,"Москва, Бутиковский переулок, 5",3000000.0,358.0,8379.89
4766,274270529,"Москва, Бутиковский переулок, 5",3000000.0,358.0,8379.89
14237,268954105,"Москва, Бутиковский переулок, 5",3000000.0,358.0,8379.89
14238,268953362,"Москва, Бутиковский переулок, 5",3000000.0,358.0,8379.89

In [46]:
display(
    df_rub.loc[
        df_rub["ID  объявления"] == 272551392,
        ["ID  объявления", "Цена", "Площадь, м2", "Описание"]
    ].T
)

                                                             2974
ID  объявления                                          272551392
Цена            1290000.0 руб./ За месяц, Срок аренды - На нес...
Площадь, м2                                                 105.0
Описание        Люксовый апартамент с дизайнерским ремонтом дл...

In [47]:
display(
    df_rub.nsmallest(10, "Общая площадь")[
        ["ID  объявления", "Адрес", "Цена числом", "Общая площадь", "Площадь, м2"]
    ]
)

,ID объявления,Адрес,Цена числом,Общая площадь,"Площадь, м2"
15105,275003684,"Москва, улица Кашенкин Луг, 11",38000.0,7.0,7.0
1556,274944164,"Москва, Цимлянская улица, 3к3",22000.0,10.0,10.0/7.0/2.0
6313,274414358,"Москва, Дегунинская улица, 1К3",30000.0,11.0,11.0/8.0/2.0
11245,239966898,"Москва, Ярославское шоссе, 124",20000.0,11.0,11.0/8.0
5230,261704536,"Москва, Клинская улица, 4К2",27000.0,12.0,12.0
6282,228524680,"Москва, Дегунинская улица, 1К3",28000.0,12.0,12.0
9559,263627242,"Москва, улица Каховка, 26",30000.0,12.0,12.0/7.0/2.0
16804,274043283,"Москва, Байкальская улица, 26/10",23000.0,12.0,12.0/9.0/3.0
17119,268870682,"Москва, Подъемная улица, 14С37",35000.0,12.0,12.0/7.0/3.0
23208,274517168,"Москва, Солнцевский проспект, 9К2, ш. Боровско...",30000.0,12.0,12.0/6.0/3.0

In [48]:
display(
    df_rub.loc[
        df_rub["ID  объявления"] == 275003684,
        ["ID  объявления", "Цена", "Площадь, м2", "Описание"]
    ].T
)

                                                            15105
ID  объявления                                          275003684
Цена            38000.0 руб./ За месяц, Залог - 38000 руб., Ко...
Площадь, м2                                                   7.0
Описание        Сдаю на долгий срок квартиру на втором этаже, ...

In [49]:
(df_rub["Общая площадь"] < 15).sum()

np.int64(47)

In [50]:
display(
    df_rub.loc[
        df_rub["Общая площадь"] < 15,
        ["ID  объявления", "Адрес", "Цена числом", "Общая площадь", "Площадь, м2"]
    ].sort_values("Общая площадь")
)

,ID объявления,Адрес,Цена числом,Общая площадь,"Площадь, м2"
15105,275003684,"Москва, улица Кашенкин Луг, 11",38000.0,7.0,7.0
1556,274944164,"Москва, Цимлянская улица, 3к3",22000.0,10.0,10.0/7.0/2.0
11245,239966898,"Москва, Ярославское шоссе, 124",20000.0,11.0,11.0/8.0
6313,274414358,"Москва, Дегунинская улица, 1К3",30000.0,11.0,11.0/8.0/2.0
5230,261704536,"Москва, Клинская улица, 4К2",27000.0,12.0,12.0
9559,263627242,"Москва, улица Каховка, 26",30000.0,12.0,12.0/7.0/2.0
6282,228524680,"Москва, Дегунинская улица, 1К3",28000.0,12.0,12.0
16804,274043283,"Москва, Байкальская улица, 26/10",23000.0,12.0,12.0/9.0/3.0
17119,268870682,"Москва, Подъемная улица, 14С37",35000.0,12.0,12.0/7.0/3.0
23208,274517168,"Москва, Солнцевский проспект, 9К2, ш. Боровско...",30000.0,12.0,12.0/6.0/3.0
19729,266990420,"Санкт-Петербург, Большой Сампсониевский проспе...",30000.0,12.3,12.3
3960,236789779,"Москва, 9-я Парковая улица, 66К2",26000.0,13.0,13.0/8.0/3.0
7350,274935565,"Москва, Яхромская улица, 3",37500.0,13.0,13.0
1829,249819541,"Москва, Волжский бульвар, 41К4",23000.0,13.0,13.0/9.0/3.0
2683,274875441,"Москва, Фестивальная улица, 52К1",30000.0,13.0,13.0
5208,273645696,"Москва, Клинская улица, 4К2",28000.0,13.0,13.0
17116,274902638,"Москва, Подъемная улица, 14С37",30000.0,13.0,13.0/5.0/4.0
17203,266018445,"Москва, Подъемная улица, 14С25",48000.0,13.0,13.0/10.0/1.0
19970,274453462,"Санкт-Петербург, проспект Средний Васильевског...",25000.0,13.0,13.0/10.0/2.0
17205,268824507,"Москва, Подъемная улица, 14С25",25000.0,13.0,13.0/11.0
15010,272679813,"Москва, 1-й Грайвороновский проезд, 2А",29000.0,13.0,13.0/10.0/2.0
21534,274357920,"Москва, Минусинская улица, 11",30000.0,13.0,13.0
13546,274057159,"Москва, проспект Вернадского, 41С1",30000.0,13.3,13.3/13.3
11246,169086145,"Москва, Ярославское шоссе, 124",21000.0,14.0,14.0/8.0
13551,273591120,"Москва, проспект Вернадского, 41С1",45000.0,14.0,14.0/8.0/3.0
7064,268332264,"Москва, проезд Серебрякова, 11к1",31990.0,14.0,14.0
4410,274772501,"Москва, улица Буракова, 1К1",26000.0,14.0,14.0/9.0/3.0
4352,274829585,"Москва, улица Буракова, 1К1",28000.0,14.0,14.0/9.0/3.0
2690,266029609,"Москва, Фестивальная улица, 52",30000.0,14.0,14.0/8.0/4.0
11466,273626820,"Москва, бульвар Генерала Карбышева, 19К5",28000.0,14.0,14.0/11.0
2720,274259876,"Москва, Автомоторная улица, 3К1",20000.0,14.0,14.0/8.0/4.0
3917,273791617,"Москва, 9-я Парковая улица, 66К2",27000.0,14.0,14.0/9.0/3.0
8389,268820958,"Москва, Нахимовский проспект, 2",46000.0,14.0,14.0/14.0
17170,267748891,"Москва, Подъемная улица, 14С25",33000.0,14.0,14.0/10.0
16249,273570611,"Санкт-Петербург, Рузовская улица, 33",15500.0,14.0,14.0
15095,273893047,"Москва, Гостиничный проезд, 8К1",30000.0,14.0,14.0/3.0
14963,273490097,"Москва, Волжский бульвар, 8К3",28000.0,14.0,14.0/7.0/3.0
13573,273646879,"Москва, проспект Вернадского, 41",35000.0,14.0,14.0
13547,274294401,"Москва, проспект Вернадского, 41С1",35000.0,14.0,14.0/8.0
15052,274064070,"Москва, Волжский бульвар, 8К3",28000.0,14.0,14.0/12.0
23209,272632468,"Москва, Солнцевский проспект, 9К2, ш. Боровско...",30000.0,14.0,14.0/7.0/4.0
17113,272772540,"Москва, Подъемная улица, 14С37",26000.0,14.0,14.0/10.0
17121,274039104,"Москва, Подъемная улица, 14С44",35000.0,14.4,14.4/12.0/1.5
5606,272653359,"Москва, 1-й Грайвороновский проезд, 2А",30000.0,14.5,14.5/10.0/2.0
13606,273310976,"Москва, проспект Вернадского, 41С1",50000.0,14.5,14.5/10.0/2.0
13608,274584577,"Москва, проспект Вернадского, 41С1",50000.0,14.5,14.5/10.0/4.5
19732,266610700,"Санкт-Петербург, Большой Сампсониевский проспе...",33000.0,14.8,14.8/2.1

In [51]:
df_rub["ID  объявления"].duplicated().sum()

np.int64(0)

In [52]:
display(df_rub[["Цена числом", "Общая площадь", "Цена за м²"]].isna().sum())

Цена числом      0
Общая площадь    0
Цена за м²       0
dtype: int64

In [53]:
print("Цена меньше или равна нулю:", (df_rub["Цена числом"] <= 0).sum())
print("Площадь меньше или равна нулю:", (df_rub["Общая площадь"] <= 0).sum())
print("Цена за м² меньше или равна нулю:", (df_rub["Цена за м²"] <= 0).sum())

Цена меньше или равна нулю: 0
Площадь меньше или равна нулю: 0
Цена за м² меньше или равна нулю: 0

In [54]:
df_rub.isna().sum()

ID  объявления                  0
Количество комнат            1041
Тип                             0
Метро                        1314
Адрес                           0
Площадь, м2                     0
Дом                             0
Парковка                    13405
Цена                            0
Телефоны                        0
Описание                        0
Ремонт                       2751
Площадь комнат, м2           8898
Балкон                       7970
Окна                         6608
Санузел                      2670
Можно с детьми/животными     6092
Дополнительно                 356
Название ЖК                 17508
Серия дома                  21184
Высота потолков, м          12148
Лифт                         5496
Мусоропровод                10505
Ссылка на объявление            0
Валюта                          0
Цена числом                     0
Общая площадь                   0
Цена за м²                      0
dtype: int64

In [55]:
missing = df_rub.isna().sum()

In [56]:
missing_table = pd.DataFrame({
    "Пропуски": missing,
    "Процент пропусков": missing_percent
})

In [57]:
display(
    missing_table[missing_table["Пропуски"] > 0]
    .sort_values("Процент пропусков", ascending=False)
)

                          Пропуски  Процент пропусков
Серия дома                   21184              90.74
Название ЖК                  17508              74.97
Парковка                     13405              57.42
Высота потолков, м           12148              52.05
Мусоропровод                 10505              45.03
Площадь комнат, м2            8898              38.13
Балкон                        7970              34.14
Окна                          6608              28.30
Можно с детьми/животными      6092              26.09
Лифт                          5496              23.54
Ремонт                        2751              11.79
Санузел                       2670              11.43
Метро                         1314               5.63
Количество комнат             1041               4.45
Дополнительно                  356               1.53

In [58]:
columns_to_check = [
    "Серия дома",
    "Название ЖК",
    "Парковка",
    "Высота потолков, м",
    "Мусоропровод",
    "Площадь комнат, м2",
    "Балкон",
    "Окна",
    "Можно с детьми/животными",
    "Лифт",
    "Ремонт",
    "Санузел",
    "Метро",
    "Количество комнат",
    "Дополнительно",
]

for column in columns_to_check:
    print(f"\n--- {column} ---")
    display(df_rub[column].value_counts(dropna=False).head(10))

--- Серия дома ---

Серия дома
NaN                      21184
индивидуальный проект      613
Индивидуальный проект      138
П44                         89
П44Т                        63
монолит                     38
СЭМ-2                       32
II-29                       29
П-44                        23
КОПЭ                        22
Name: count, dtype: int64

--- Название ЖК ---

Название ЖК
NaN                       17508
Символ, 2019                 61
Водный, 2015                 45
Квартал на Ленинском         37
Метрополия, 2021             36
Триумф-Палас, 2006           35
Люблинский парк              33
Октябрьское поле, 2021       28
Триумф-Палас                 28
Аэробус, 2008                26
Name: count, dtype: int64

--- Парковка ---

Парковка
NaN               13405
наземная           6042
подземная          2761
открытая           1017
многоуровневая      118
на крыше              1
Name: count, dtype: int64

--- Высота потолков, м ---

Высота потолков, м
NaN     12148
2.64     4467
3.00     1317
2.70     1040
2.48      676
3.20      615
2.60      543
2.80      531
2.50      463
2.75      221
Name: count, dtype: int64

--- Мусоропровод ---

Мусоропровод
Да     10890
NaN    10505
Нет     1949
Name: count, dtype: int64

--- Площадь комнат, м2 ---

Площадь комнат, м2
NaN      8898
20       1620
18        952
19        765
17        284
16        266
21        262
18-14     261
15        229
18-12     224
Name: count, dtype: int64

--- Балкон ---

Балкон
NaN                       7970
Балкон (1)                7421
Лоджия (1)                6004
Балкон (1), Лоджия (1)     714
Лоджия (2)                 568
Балкон (2)                 474
Балкон (3)                  54
Лоджия (3)                  42
Балкон (2), Лоджия (2)      25
Балкон (1), Лоджия (2)      24
Name: count, dtype: int64

--- Окна ---

Окна
Во двор            10863
NaN                 6608
На улицу и двор     3285
На улицу            2588
Name: count, dtype: int64

--- Можно с детьми/животными ---

Можно с детьми/животными
Можно с детьми                       10127
Можно с детьми, Можно с животными     6886
NaN                                   6092
Можно с животными                      239
Name: count, dtype: int64

--- Лифт ---

Лифт
Пасс (1)              5904
NaN                   5496
Пасс (2)              4325
Пасс (1), Груз (1)    3957
Пасс (2), Груз (1)    1220
Пасс (2), Груз (2)     652
Пасс (3)               636
Пасс (4)               346
Пасс (3), Груз (1)     187
Пасс (1), Груз (2)     185
Name: count, dtype: int64

--- Ремонт ---

Ремонт
Косметический    8498
Евроремонт       8462
Дизайнерский     3463
NaN              2751
Без ремонта       170
Name: count, dtype: int64

--- Санузел ---

Санузел
Совмещенный (1)                    10078
Раздельный (1)                      7158
NaN                                 2670
Совмещенный (2)                     1431
Совмещенный (1), Раздельный (1)      810
Раздельный (2)                       533
Совмещенный (3)                      237
Совмещенный (2), Раздельный (1)      187
Совмещенный (4)                       72
Раздельный (3)                        52
Name: count, dtype: int64

--- Метро ---

Метро
NaN                                 1314
м. Академическая (10 мин пешком)      41
м. Водный стадион (5 мин пешком)      40
м. Приморская (None мин пешком)       35
м. Щелковская (15 мин пешком)         34
м. Строгино (15 мин пешком)           33
м. Римская (None мин пешком)          33
м. Динамо (7 мин пешком)              33
м. Кузьминки (10 мин пешком)          32
м. Коломенская (15 мин пешком)        31
Name: count, dtype: int64

--- Количество комнат ---

Количество комнат
1                   7917
2, Изолированная    4623
2                   2591
3                   1715
3, Изолированная    1583
NaN                 1041
3, Оба варианта      875
4                    670
2, Смежная           637
2, Оба варианта      615
Name: count, dtype: int64

--- Дополнительно ---

Дополнительно
Мебель в комнатах, Мебель на кухне, Ванна, Стиральная машина, Телевизор, Холодильник, Интернет                                                                2896
Мебель в комнатах, Мебель на кухне, Ванна, Стиральная машина, Холодильник, Интернет                                                                           1318
Мебель в комнатах, Мебель на кухне, Ванна, Стиральная машина, Кондиционер, Посудомоечная машина, Телевизор, Холодильник, Интернет                             1042
Мебель в комнатах, Мебель на кухне, Ванна, Стиральная машина, Кондиционер, Телевизор, Холодильник, Интернет                                                    967
Мебель в комнатах, Мебель на кухне, Ванна, Стиральная машина, Телевизор, Холодильник, Интернет, Телефон                                                        887
Мебель в комнатах, Мебель на кухне, Стиральная машина, Холодильник                                                                                             868
Мебель в комнатах, Мебель на кухне, Ванна, Душевая кабина, Стиральная машина, Кондиционер, Посудомоечная машина, Телевизор, Холодильник, Интернет, Телефон     768
Мебель в комнатах, Мебель на кухне, Ванна, Душевая кабина, Стиральная машина, Кондиционер, Посудомоечная машина, Телевизор, Холодильник, Интернет              725
Мебель в комнатах, Мебель на кухне, Ванна, Стиральная машина, Телевизор, Холодильник                                                                           644
Мебель в комнатах, Мебель на кухне, Ванна, Стиральная машина, Кондиционер, Посудомоечная машина, Телевизор, Холодильник, Интернет, Телефон                     602
Name: count, dtype: int64

In [59]:
df_rub["Высота потолков, м"].describe()

count    11196.000000
mean         2.983292
std          7.618112
min          1.200000
25%          2.640000
50%          2.640000
75%          2.800000
max        320.000000
Name: Высота потолков, м, dtype: float64

In [60]:
df_rub.loc[
    df_rub["Высота потолков, м"] > 10,
    ["ID  объявления", "Адрес", "Высота потолков, м"]
].sort_values(
    "Высота потолков, м",
    ascending=False
)

,ID объявления,Адрес,"Высота потолков, м"
11189,274140593,"Москва, Профсоюзная улица, 7/12",320.0
8625,272179535,"Москва, Мясницкая улица, 21/8с8",320.0
9,272900409,"Москва, улица Арбат, 30/3С1",310.0
17134,274849798,"Москва, Нижегородская улица, 86кБ",280.0
9280,274998351,"Москва, Болотниковская улица, 30",265.0
12636,274906525,"Москва, улица 1812 года, 8К2",264.0
3759,274982211,"Москва, Борисовский проезд, 8К2",264.0
247,271203810,"Москва, Долгопрудная аллея, 14к1, ш. Дмитровск...",260.0
8832,232362985,"Москва, улица Винокурова, 22К2",28.0
2969,274867097,"Москва, Каширский проезд, 25к1",28.0
21584,265857148,"Москва, улица Коминтерна, 15",28.0
11123,271267183,"Москва, Ленинский проспект, 95Б",27.0
4072,252733003,"Москва, Полярная улица, 27к4",27.0
8382,166609594,"Москва, Балаклавский проспект, 10К3",27.0
22070,273432181,"Москва, Автозаводская улица, 23С120",27.0
7423,274946733,"Москва, Варшавское шоссе, 49к1",26.0
15769,219565783,"Москва, Кременчугская улица, 40К1",25.0
6616,274903162,"Москва, Красноказарменная улица, 14Ак1",12.8

In [61]:
df_rub.loc[
    df_rub["Высота потолков, м"] > 10,
    "Высота потолков, м"
] = np.nan

In [62]:
df_rub["Высота потолков, м"].median()

np.float64(2.64)

In [63]:
ceiling_median = df_rub["Высота потолков, м"].median()

In [64]:
df_rub["Высота потолков, м"].fillna(ceiling_median)

0        3.00
1        3.50
2        3.20
3        3.20
4        3.90
         ...
23363    2.64
23364    2.64
23365    2.64
23366    2.65
23367    2.64
Name: Высота потолков, м, Length: 23344, dtype: float64

In [65]:
df_rub["Высота потолков, м"] = df_rub["Высота потолков, м"].fillna(ceiling_median)

In [66]:
print("Медиана высоты потолков:", ceiling_median)
print("Количество пропусков:", df_rub["Высота потолков, м"].isna().sum())
print("Максимальная высота:", df_rub["Высота потолков, м"].max())
print()
print("Минимальная высота:", df_rub["Высота потолков, м"].min())

Медиана высоты потолков: 2.64
Количество пропусков: 0
Максимальная высота: 9.0

Минимальная высота: 1.2

In [67]:
df_rub.loc[df_rub["Высота потолков, м"] == 1.2]

,ID объявления,Количество комнат,Тип,Метро,Адрес,"Площадь, м2",Дом,Парковка,Цена,Телефоны,...,Название ЖК,Серия дома,"Высота потолков, м",Лифт,Мусоропровод,Ссылка на объявление,Валюта,Цена числом,Общая площадь,Цена за м²
22265,274439221,3,Квартира,м. Менделеевская (15 мин пешком),"Москва, Октябрьский переулок, 9",116.0/30.0,"3/13, Монолитный",NaN,"165000.0 руб./ За месяц, Залог - 165000 руб., ...","+79651152129, +79623678610",...,NaN,NaN,1.2,Пасс (1),NaN,https://www.cian.ru/rent/flat/274439221,руб.,165000.0,116.0,1422.41

In [68]:
display(pd.DataFrame({
    "Столбец": df_rub.columns,
    "Тип данных": df_rub.dtypes.astype(str).values,
    "Пропуски": df_rub.isna().sum().values,
    "Уникальных значений": df_rub.nunique().values
}))

                     Столбец Тип данных  Пропуски  Уникальных значений
0             ID  объявления      int64         0                23344
1          Количество комнат        str      1041                   24
2                        Тип        str         0                    1
3                      Метро        str      1314                 5864
4                      Адрес        str         0                12848
5                Площадь, м2        str         0                11237
6                        Дом        str         0                 2564
7                   Парковка        str     13405                    5
8                       Цена        str         0                 3904
9                   Телефоны        str         0                13166
10                  Описание        str         0                23054
11                    Ремонт        str      2751                    4
12        Площадь комнат, м2        str      8898                 3980
13                    Балкон        str      7970                   18
14                      Окна        str      6608                    3
15                   Санузел        str      2670                   20
16  Можно с детьми/животными        str      6092                    3
17             Дополнительно        str       356                  527
18               Название ЖК        str     17508                 1797
19                Серия дома        str     21184                  393
20        Высота потолков, м    float64         0                   84
21                      Лифт        str      5496                   34
22              Мусоропровод        str     10505                    2
23      Ссылка на объявление        str         0                23344
24                    Валюта        str         0                    1
25               Цена числом    float64         0                  593
26             Общая площадь    float64         0                 1009
27                Цена за м²    float64         0                 4648

In [69]:
df_rub["Количество комнат"].value_counts(dropna=False)

Количество комнат
1                   7917
2, Изолированная    4623
2                   2591
3                   1715
3, Изолированная    1583
NaN                 1041
3, Оба варианта      875
4                    670
2, Смежная           637
2, Оба варианта      615
4, Оба варианта      252
5                    229
4, Изолированная     223
3, Смежная            87
6                     80
5, Оба варианта       79
5, Изолированная      47
6, Оба варианта       30
6, Изолированная      16
4, Смежная            13
1, Изолированная       8
1, Оба варианта        4
5, Смежная             4
6, Смежная             3
1, Смежная             2
Name: count, dtype: int64

In [70]:
df_rub[["Количество комнат"]].sample(10, random_state=42)

      Количество комнат
13551               NaN
7812   2, Изолированная
20768  2, Изолированная
13366  2, Изолированная
12848                 3
247                   1
9440   3, Изолированная
2710    2, Оба варианта
3444                  2
3429                  3

In [71]:
df_rub["rooms"] = (
    df_rub["Количество комнат"]
    .str.extract(r"^(\d+)")[0]
    .astype(float)
)

df_rub["room_layout"] = (
    df_rub["Количество комнат"]
    .str.extract(r",\s*(.+)$")[0]
)

In [72]:
display(
    df_rub[
        ["Количество комнат", "rooms", "room_layout"]
    ].sample(10, random_state=42)
)

      Количество комнат  rooms    room_layout
13551               NaN    NaN            NaN
7812   2, Изолированная    2.0  Изолированная
20768  2, Изолированная    2.0  Изолированная
13366  2, Изолированная    2.0  Изолированная
12848                 3    3.0            NaN
247                   1    1.0            NaN
9440   3, Изолированная    3.0  Изолированная
2710    2, Оба варианта    2.0   Оба варианта
3444                  2    2.0            NaN
3429                  3    3.0            NaN

In [73]:
print("Пропуски в rooms:", df_rub["rooms"].isna().sum())
print("Пропуски в room_layout:", df_rub["room_layout"].isna().sum())

print("\nВарианты планировки:")
display(df_rub["room_layout"].value_counts(dropna=False))

Пропуски в rooms: 1041
Пропуски в room_layout: 14243

Варианты планировки:

room_layout
NaN              14243
Изолированная     6500
Оба варианта      1855
Смежная            746
Name: count, dtype: int64

In [74]:
for column in df_rub.select_dtypes(include="number").columns:
    df_rub[column] = df_rub[column].fillna(df_rub[column].median())

In [75]:
for column in df_rub.select_dtypes(include=["object", "str"]).columns:
    df_rub[column] = df_rub[column].fillna("unknown")

In [76]:
print("Всего пропусков:", df_rub.isna().sum().sum())

Всего пропусков: 0

In [77]:
df_rub = df_rub.rename(columns={
    "ID  объявления": "id",
    "Количество комнат": "rooms_original",
    "Тип": "property_type",
    "Метро": "metro",
    "Адрес": "address",
    "Площадь, м2": "area_original",
    "Дом": "building",
    "Парковка": "parking",
    "Цена": "price_original",
    "Телефоны": "phones",
    "Описание": "description",
    "Ремонт": "renovation",
    "Площадь комнат, м2": "room_area",
    "Балкон": "balcony",
    "Окна": "windows",
    "Санузел": "bathroom",
    "Можно с детьми/животными": "pets_children_allowed",
    "Дополнительно": "amenities",
    "Название ЖК": "residential_complex",
    "Серия дома": "building_series",
    "Высота потолков, м": "ceiling_height",
    "Лифт": "elevator",
    "Мусоропровод": "garbage_chute",
    "Ссылка на объявление": "listing_url",
    "Валюта": "currency",
    "Цена числом": "price",
    "Общая площадь": "total_area",
    "Цена за м²": "price_per_sqm",
    "rooms": "rooms",
    "room_layout": "room_layout"
})

print(df_rub.columns.tolist())

['id', 'rooms_original', 'property_type', 'metro', 'address', 'area_original', 'building', 'parking', 'price_original', 'phones', 'description', 'renovation', 'room_area', 'balcony', 'windows', 'bathroom', 'pets_children_allowed', 'amenities', 'residential_complex', 'building_series', 'ceiling_height', 'elevator', 'garbage_chute', 'listing_url', 'currency', 'price', 'total_area', 'price_per_sqm', 'rooms', 'room_layout']

In [78]:
df_rub["metro_station"] = (
    df_rub["metro"]
    .str.extract(r"м\.\s*(.*?)\s*\(")[0]
)

df_rub["metro_walk_minutes"] = pd.to_numeric(
    df_rub["metro"].str.extract(r"\((\d+)\s*мин пешком\)")[0],
    errors="coerce"
)

In [79]:
display(df_rub[["metro", "metro_station", "metro_walk_minutes"]].head(10))

                          metro metro_station  metro_walk_minutes
0  м. Смоленская (9 мин пешком)    Смоленская                 9.0
1  м. Смоленская (8 мин пешком)    Смоленская                 8.0
2  м. Смоленская (7 мин пешком)    Смоленская                 7.0
3  м. Смоленская (3 мин пешком)    Смоленская                 3.0
4   м. Арбатская (7 мин пешком)     Арбатская                 7.0
5  м. Смоленская (5 мин пешком)    Смоленская                 5.0
6   м. Арбатская (4 мин пешком)     Арбатская                 4.0
7  м. Смоленская (3 мин пешком)    Смоленская                 3.0
8  м. Смоленская (9 мин пешком)    Смоленская                 9.0
9  м. Арбатская (10 мин пешком)     Арбатская                10.0

In [80]:
df_rub["floor"] = pd.to_numeric(
    df_rub["building"].str.extract(r"(\d+)\s*/")[0],
    errors="coerce"
)

df_rub["total_floors"] = pd.to_numeric(
    df_rub["building"].str.extract(r"/\s*(\d+)")[0],
    errors="coerce"
)

display(df_rub[["building", "floor", "total_floors"]].head(5))

                    building  floor  total_floors
0           5/16, Монолитный      5            16
1  5/16, Монолитно-кирпичный      5            16
2                       5/16      5            16
3                        5/6      5             6
4           12/26, Панельный     12            26

In [81]:
df_rub["passenger_elevators"] = pd.to_numeric(
    df_rub["elevator"].str.extract(r"Пасс\s*\((\d+)\)")[0],
    errors="coerce"
)

df_rub["freight_elevators"] = pd.to_numeric(
    df_rub["elevator"].str.extract(r"Груз\s*\((\d+)\)")[0],
    errors="coerce"
)

display(df_rub[["elevator", "passenger_elevators", "freight_elevators"]].head(5))

             elevator  passenger_elevators  freight_elevators
0  Пасс (4), Груз (1)                  4.0                1.0
1  Пасс (1), Груз (1)                  1.0                1.0
2            Пасс (1)                  1.0                NaN
3            Пасс (1)                  1.0                NaN
4  Пасс (1), Груз (1)                  1.0                1.0

In [82]:
df_rub["balconies"] = pd.to_numeric(
    df_rub["balcony"].str.extract(r"Балкон\s*\((\d+)\)")[0],
    errors="coerce"
)

df_rub["loggias"] = pd.to_numeric(
    df_rub["balcony"].str.extract(r"Лоджия\s*\((\d+)\)")[0],
    errors="coerce"
)
display(df_rub[["loggias", "balconies", "balcony"]].sample(10))

       loggias  balconies                 balcony
12673      NaN        1.0              Балкон (1)
5691       1.0        NaN              Лоджия (1)
2645       1.0        NaN              Лоджия (1)
9631       NaN        1.0              Балкон (1)
22992      1.0        NaN              Лоджия (1)
11375      1.0        1.0  Балкон (1), Лоджия (1)
6884       NaN        1.0              Балкон (1)
3251       NaN        NaN                 unknown
2546       NaN        NaN                 unknown
9280       2.0        NaN              Лоджия (2)

In [83]:
df_rub["combined_bathrooms"] = pd.to_numeric(
    df_rub["bathroom"].str.extract(r"Совмещенный\s*\((\d+)\)")[0],
    errors="coerce"
)

df_rub["separate_bathrooms"] = pd.to_numeric(
    df_rub["bathroom"].str.extract(r"Раздельный\s*\((\d+)\)")[0],
    errors="coerce"
)

In [84]:
display(df_rub[
    [
        "rooms",
        "room_layout",
        "metro_station",
        "metro_walk_minutes",
        "floor",
        "total_floors",
        "passenger_elevators",
        "freight_elevators",
        "balconies",
        "loggias",
        "combined_bathrooms",
        "separate_bathrooms"
    ]
].head())

,rooms,room_layout,metro_station,metro_walk_minutes,floor,total_floors,passenger_elevators,freight_elevators,balconies,loggias,combined_bathrooms,separate_bathrooms
0,4.0,unknown,Смоленская,9.0,5,16,4.0,1.0,NaN,NaN,NaN,NaN
1,4.0,unknown,Смоленская,8.0,5,16,1.0,1.0,NaN,NaN,2.0,1.0
2,4.0,Оба варианта,Смоленская,7.0,5,16,1.0,NaN,NaN,NaN,3.0,NaN
3,4.0,Оба варианта,Смоленская,3.0,5,6,1.0,NaN,NaN,NaN,3.0,NaN
4,2.0,unknown,Арбатская,7.0,12,26,1.0,1.0,NaN,NaN,2.0,NaN

In [85]:
df_rub["children_allowed"] = (
    df_rub["pets_children_allowed"]
    .str.contains("Можно с детьми", na=False)
    .astype(int)
)

df_rub["pets_allowed"] = (
    df_rub["pets_children_allowed"]
    .str.contains("Можно с животными", na=False)
    .astype(int)
)

In [86]:
df_rub["furniture"] = (
    df_rub["amenities"]
    .str.contains("Мебель", na=False)
    .astype(int)
)

In [87]:
df_rub["washing_machine"] = (
    df_rub["amenities"]
    .str.contains("Стиральная машина", na=False)
    .astype(int)
)

In [88]:
df_rub["dishwasher"] = (
    df_rub["amenities"]
    .str.contains("Посудомоечная машина", na=False)
    .astype(int)
)

In [89]:
df_rub["air_conditioner"] = (
    df_rub["amenities"]
    .str.contains("Кондиционер", na=False)
    .astype(int)
)

In [90]:
display(
    df_rub.sample(5)[[
        "children_allowed",
        "pets_allowed",
        "furniture",
        "washing_machine",
        "air_conditioner",
        "dishwasher"
]])

,children_allowed,pets_allowed,furniture,washing_machine,air_conditioner,dishwasher
5295,1,1,1,1,0,0
1835,1,1,1,1,0,0
16268,1,1,1,0,1,0
7864,1,1,1,1,0,0
19772,1,1,1,0,0,0

In [91]:
categorical_columns = [
    "room_layout",
    "parking",
    "renovation",
    "windows",
    "garbage_chute",
    "property_type",
    "currency",
]

for column in categorical_columns:
    df_rub[column] = df_rub[column].astype("category").cat.codes

In [92]:
numeric_columns = df_rub.select_dtypes(include="number").columns

In [93]:
for column in numeric_columns:
    if df_rub[column].isna().any():
        df_rub[column] = df_rub[column].fillna(df_rub[column].median())

In [94]:
print("Всего пропусков:", df_rub.isna().sum().sum())

Всего пропусков: 1314

In [95]:
df_rub.isna().sum().loc[lambda x: x > 0]

metro_station    1314
dtype: int64

In [96]:
df_rub["metro_station"] = df_rub["metro_station"].fillna("unknown")

In [97]:
print("Всего пропусков:", df_rub.isna().sum().sum())

Всего пропусков: 0

In [98]:
df_rub.to_csv("../data_processed/data.csv", index=False)

In [99]:
print("Размер таблицы:", df_rub.shape)
print("Количество пропусков:", df_rub.isna().sum().sum())
print(df_rub.columns.tolist())
df_rub.info()

Размер таблицы: (23344, 46)
Количество пропусков: 0
['id', 'rooms_original', 'property_type', 'metro', 'address', 'area_original', 'building', 'parking', 'price_original', 'phones', 'description', 'renovation', 'room_area', 'balcony', 'windows', 'bathroom', 'pets_children_allowed', 'amenities', 'residential_complex', 'building_series', 'ceiling_height', 'elevator', 'garbage_chute', 'listing_url', 'currency', 'price', 'total_area', 'price_per_sqm', 'rooms', 'room_layout', 'metro_station', 'metro_walk_minutes', 'floor', 'total_floors', 'passenger_elevators', 'freight_elevators', 'balconies', 'loggias', 'combined_bathrooms', 'separate_bathrooms', 'children_allowed', 'pets_allowed', 'furniture', 'washing_machine', 'dishwasher', 'air_conditioner']
<class 'pandas.DataFrame'>
Index: 23344 entries, 0 to 23367
Data columns (total 46 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     23344 non-null  int64
 1   rooms_original         23344 non-null  str
 2   property_type          23344 non-null  int8
 3   metro                  23344 non-null  str
 4   address                23344 non-null  str
 5   area_original          23344 non-null  str
 6   building               23344 non-null  str
 7   parking                23344 non-null  int8
 8   price_original         23344 non-null  str
 9   phones                 23344 non-null  str
 10  description            23344 non-null  str
 11  renovation             23344 non-null  int8
 12  room_area              23344 non-null  str
 13  balcony                23344 non-null  str
 14  windows                23344 non-null  int8
 15  bathroom               23344 non-null  str
 16  pets_children_allowed  23344 non-null  str
 17  amenities              23344 non-null  str
 18  residential_complex    23344 non-null  str
 19  building_series        23344 non-null  str
 20  ceiling_height         23344 non-null  float64
 21  elevator               23344 non-null  str
 22  garbage_chute          23344 non-null  int8
 23  listing_url            23344 non-null  str
 24  currency               23344 non-null  int8
 25  price                  23344 non-null  float64
 26  total_area             23344 non-null  float64
 27  price_per_sqm          23344 non-null  float64
 28  rooms                  23344 non-null  float64
 29  room_layout            23344 non-null  int8
 30  metro_station          23344 non-null  str
 31  metro_walk_minutes     23344 non-null  float64
 32  floor                  23344 non-null  int64
 33  total_floors           23344 non-null  int64
 34  passenger_elevators    23344 non-null  float64
 35  freight_elevators      23344 non-null  float64
 36  balconies              23344 non-null  float64
 37  loggias                23344 non-null  float64
 38  combined_bathrooms     23344 non-null  float64
 39  separate_bathrooms     23344 non-null  float64
 40  children_allowed       23344 non-null  int64
 41  pets_allowed           23344 non-null  int64
 42  furniture              23344 non-null  int64
 43  washing_machine        23344 non-null  int64
 44  dishwasher             23344 non-null  int64
 45  air_conditioner        23344 non-null  int64
dtypes: float64(12), int64(9), int8(7), str(18)
memory usage: 44.9 MB

In [100]:
df_final = df_rub.select_dtypes(include="number").copy()

In [101]:
df_final = df_final.drop_duplicates(subset="id")

In [102]:
print("Размер таблицы:", df_final.shape)
print("Дубликаты ID:", df_final["id"].duplicated().sum())
print("Пропуски:", df_final.isna().sum().sum())
print("Все столбцы числовые:", df_final.select_dtypes(exclude="number").shape[1] == 0)

Размер таблицы: (23344, 28)
Дубликаты ID: 0
Пропуски: 0
Все столбцы числовые: True

In [103]:
df_final.to_csv("../data_processed/final_data.csv", index=False)

In [104]:
df_final["price"].describe()

count    2.334400e+04
mean     8.296726e+04
std      1.227379e+05
min      1.000000e+04
25%      3.700000e+04
50%      4.990000e+04
75%      7.500000e+04
max      3.000000e+06
Name: price, dtype: float64

In [106]:
print(df_final.columns)

Index(['id', 'property_type', 'parking', 'renovation', 'windows',
       'ceiling_height', 'garbage_chute', 'currency', 'price', 'total_area',
       'price_per_sqm', 'rooms', 'room_layout', 'metro_walk_minutes', 'floor',
       'total_floors', 'passenger_elevators', 'freight_elevators', 'balconies',
       'loggias', 'combined_bathrooms', 'separate_bathrooms',
       'children_allowed', 'pets_allowed', 'furniture', 'washing_machine',
       'dishwasher', 'air_conditioner'],
      dtype='str')